# Generated by Django 4.1.2 on 2022-10-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_created_at_user_end_date_user_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
