# Generated by Django 4.1.1 on 2022-09-13 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import product.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='null', max_length=125, unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(default='null', max_length=125, unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(default='null', max_length=125, unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.TextField(blank=True)),
                ('remaining_stock', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('brand', models.ForeignKey(db_column='brand', on_delete=django.db.models.deletion.DO_NOTHING, to='product.brand', to_field='brand')),
                ('other_part_no', models.ForeignKey(db_column='other_part_no', on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_part', to='product.partno', to_field='part_no')),
                ('part_no', models.ForeignKey(db_column='part_no', on_delete=django.db.models.deletion.DO_NOTHING, related_name='part', to='product.partno', to_field='part_no')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(default='null', max_length=125, unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(default='null', max_length=125, unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_no', models.CharField(default='null', max_length=125, unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email', models.EmailField(max_length=254)),
                ('employee_id', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('middle_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('joined_on', models.DateTimeField(blank=True, null=True)),
                ('job_role', models.ForeignKey(db_column='job_role', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.jobrole', to_field='job_role')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice_no', models.CharField(default=product.models.invoice_number, max_length=120)),
                ('action', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('warehouse_no', models.ForeignKey(db_column='warehouse_no', on_delete=django.db.models.deletion.DO_NOTHING, to='product.warehouse', to_field='warehouse_no')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(db_column='supplier', on_delete=django.db.models.deletion.DO_NOTHING, to='product.supplier', to_field='supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(db_column='unit', on_delete=django.db.models.deletion.DO_NOTHING, to='product.unit', to_field='unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_no',
            field=models.ForeignKey(db_column='warehouse_no', on_delete=django.db.models.deletion.DO_NOTHING, to='product.warehouse', to_field='warehouse_no'),
        ),
    ]
