# Generated by Django 4.1.1 on 2022-10-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_brand_description_jobrole_description_and_more'),
    ]

    operations = [
    ]
