# Generated by Django 4.1.2 on 2022-10-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_user'),
    ]

    operations = [
    ]
