# Generated by Django 4.1.2 on 2022-10-19 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_brand_start_date_jobrole_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partno',
            old_name='part_no',
            new_name='part',
        ),
        migrations.RemoveField(
            model_name='product',
            name='other_part_no',
        ),
        migrations.RemoveField(
            model_name='product',
            name='part_no',
        ),
        migrations.AddField(
            model_name='product',
            name='other_part',
            field=models.ForeignKey(db_column='other_part', default='NaN', on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_part_number', to='product.partno', to_field='part'),
        ),
        migrations.AddField(
            model_name='product',
            name='part',
            field=models.ForeignKey(db_column='part', default='NaN', on_delete=django.db.models.deletion.DO_NOTHING, related_name='part_number', to='product.partno', to_field='part'),
        ),
    ]
