# Generated by Django 4.1.2 on 2022-10-19 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_part_no_partno_part_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='warehouse_no',
            new_name='warehouse',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warehouse_no',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='warehouse_no',
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse', default='Nan', on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_name', to='product.warehouse', to_field='warehouse'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse', default='NaN', on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_name_t', to='product.warehouse', to_field='warehouse'),
        ),
    ]
