# Generated by Django 4.1.2 on 2022-12-10 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_warehouse_no_warehouse_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(db_column='brand', default='NaN', on_delete=django.db.models.deletion.DO_NOTHING, to='product.brand', to_field='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(db_column='supplier', default='NaN', on_delete=django.db.models.deletion.DO_NOTHING, to='product.supplier', to_field='supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(db_column='unit', default='NaN', on_delete=django.db.models.deletion.DO_NOTHING, to='product.unit', to_field='unit'),
        ),
    ]
