# Generated by Django 4.1.2 on 2022-12-19 14:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_brand_alter_product_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=240)),
                ('middle_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('employee_id', models.CharField(max_length=120)),
                ('joined_on', models.DateTimeField(blank=True, null=True)),
                ('job_role', models.ForeignKey(db_column='job_role', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.jobrole', to_field='job_role')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse', default='NaN', on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_name', to='product.warehouse', to_field='warehouse'),
        )
    ]
