# Generated by Django 4.1.2 on 2022-12-19 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_employee_created_at_employee_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(db_column='brand', on_delete=django.db.models.deletion.DO_NOTHING, to='product.brand', to_field='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='other_part',
            field=models.ForeignKey(db_column='other_part', on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_part_number', to='product.partno', to_field='part'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(db_column='supplier', on_delete=django.db.models.deletion.DO_NOTHING, to='product.supplier', to_field='supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(db_column='unit', on_delete=django.db.models.deletion.DO_NOTHING, to='product.unit', to_field='unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse', on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_name', to='product.warehouse', to_field='warehouse'),
        )
    ]
