# Generated by Django 4.1.2 on 2022-12-19 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_employee_end_date_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='joined_on',
        ),
        migrations.AddField(
            model_name='employee',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.warehouse', to_field='warehouse'),
        )
    ]
