# Generated by Django 4.1.2 on 2022-12-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_employee_joined_on_employee_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        )
    ]
