# Generated by Django 4.1.1 on 2023-01-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_inboundhistory_outboundhistory_remove_user_job_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='other_part',
            field=models.ForeignKey(db_column='other_part', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_part_number', to='product.partno', to_field='part'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(db_column='supplier', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.supplier', to_field='supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(db_column='unit', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.unit', to_field='unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_name', to='product.warehouse', to_field='warehouse'),
        ),
    ]
