# Generated by Django 4.1.1 on 2023-01-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_other_part_alter_product_supplier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboundhistory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='inboundhistory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='outboundhistory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='outboundhistory',
            old_name='user_id',
            new_name='user',
        ),
    ]
