# Generated by Django 4.1.1 on 2023-01-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_rename_product_id_inboundhistory_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundhistory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
