# Generated by Django 4.1.1 on 2023-01-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_inboundhistory_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundhistory',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='outboundhistory',
            name='warehouse',
        ),
    ]
