# Generated by Django 4.1.1 on 2023-01-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_inboundhistory_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundhistory',
            name='reference_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
