# Generated by Django 4.1.1 on 2023-01-29 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_inboundhistory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundhistory',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundhistory',
            name='warehouse_to',
            field=models.ForeignKey(db_column='warehouse_to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_name_to', to='product.warehouse', to_field='warehouse'),
        ),

    ]
