# Generated by Django 4.1.1 on 2023-01-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_inboundhistory_supplier_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='partno',
            name='other_part_no',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
