# Generated by Django 4.1.1 on 2023-02-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_partno_other_part_no_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='other_part',
        ),
        migrations.RemoveField(
            model_name='product',
            name='part',
        ),
    ]
