# Generated by Django 4.1.1 on 2023-02-03 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_remove_product_other_part_remove_product_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='part',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.partno'),
        ),
        migrations.AlterField(
            model_name='partno',
            name='part',
            field=models.CharField(default='null', max_length=125),
        ),
    ]
