# Generated by Django 4.1.1 on 2023-02-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_product_part_alter_partno_part_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partno',
            old_name='other_part_no',
            new_name='alternatives',
        ),
        migrations.AddField(
            model_name='product',
            name='alternative',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
