# Generated by Django 4.1.1 on 2023-02-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_rename_other_part_no_partno_alternatives_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='alternative',
            new_name='alternatives',
        ),
    ]
